GV-1 Add QR_Code scanner
Graffity-Technologies/graffity-viewer pull request #2
Opened 2023-09-22 08:07 UTC by f16f16f16f16

![IMG_6186](https://github.com/Graffity-Technologies/graffity-viewer/assets/82135498/8d9fe62f-59b1-4f3a-86ea-026ab9332a27)

- Add menu scanner

![IMG_6191](https://github.com/Graffity-Technologies/graffity-viewer/assets/82135498/4f0438d9-bca9-4c32-96dc-5b7711820399)

- If it is not in the right format then show the error

- Add scan window

2023-09-22 08:15 UTC, f16f16f16f16 commented on lib/main.dart
> +                  ),
New menu

2023-09-22 08:16 UTC, f16f16f16f16 commented on lib/main.dart
> +
send text from scanner to text_field

2023-09-22 08:17 UTC, f16f16f16f16 commented on lib/main.dart
> +
QRCode scanner screen

2023-09-22 08:18 UTC, f16f16f16f16 commented on lib/main.dart
> +                    ),
check if it is the right format or not

2023-09-22 09:55 UTC, bankbiz requested changes

2023-09-22 09:55 UTC, bankbiz commented on lib/main.dart
> +                if (scannedText!
To prevent null pointer ref., you should check if `scannedText` is null or not krub. Like:
```
if (scannedText == null)
{
    continue;
}
```

2023-09-22 10:47 UTC, f16f16f16f16 commented on lib/main.dart
> +                if (scannedText!
okay krub

2023-09-25 02:57 UTC, bankbiz commented on lib/main.dart
> +    if (!text.startsWith('https://viewer.graffity.app/ar/')) {
Make this prefix `https://viewer.graffity.app/ar/` to const in case we have to reuse again.

2023-09-25 02:57 UTC, bankbiz requested changes

2023-09-25 02:57 UTC, bankbiz commented on lib/main.dart
> +                    .startsWith('https://viewer.graffity.app/ar/')) {
Make this prefix `https://viewer.graffity.app/ar/` to const in case we have to reuse again.

2023-09-25 02:58 UTC, merged